name: Clipman AppImage
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: build
      run: |
        sudo apt update
        sudo apt install libfuse2 gcc xsltproc autopoint xfce4-dev-tools
        sudo apt install libncursesw5-dev autotools-dev autoconf automake build-essential meson ninja-build
        wget https://raw.githubusercontent.com/Samueru-sama/xfce4-clipman-plugin/master/Clipman-AppImage.sh
        chmod a+x ./Clipman-AppImage.sh
        ./Clipman-AppImage.sh
        mkdir dist
        mv *AppImage dist/

    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Clipman-x86_64.AppImage
        path: 'dist'
        
  release:
      needs: [build]
      permissions: write-all
      runs-on: ubuntu-latest

      steps:
        - uses: actions/download-artifact@v1
          with:
            name: Clipman-x86_64.AppImage

        - name: release
          uses: marvinpinto/action-automatic-releases@latest
          with:
            title: Continuous build
            automatic_release_tag: continuous
            prerelease: false
            draft: false
            files: |
              Clipman-x86_64.AppImage
            repo_token: ${{ secrets.GITHUB_TOKEN }}
